=== noloman/V2V/src/xml/XMLSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="aceleracion">
    <xs:complexType mixed="true" />
  </xs:element>
  <xs:element name="clima">
    <xs:complexType mixed="true" />
  </xs:element>
  <xs:element name="direccion">
    <xs:complexType mixed="true" />
  </xs:element>
  <xs:element name="distancia">
    <xs:complexType mixed="true" />
  </xs:element>
  <xs:element name="informacion_ajena">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="vehiculo" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="informacion_propia">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="distancia" />
        <xs:element ref="velocidad" />
        <xs:element ref="vmax" />
        <xs:element ref="aceleracion" />
        <xs:element ref="direccion" />
        <xs:element ref="clima" />
        <xs:element ref="tiempo" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="tiempo">
    <xs:complexType mixed="true" />
  </xs:element>
  <xs:element name="vehiculo">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="informacion_propia" minOccurs="0"/>
        <xs:element ref="informacion_ajena" minOccurs="0"/>
        
        <xs:element ref="distancia" minOccurs="0" />
        <xs:element ref="velocidad" minOccurs="0" />
        <xs:element ref="vmax" minOccurs="0" />
        <xs:element ref="aceleracion" minOccurs="0" />
        <xs:element ref="direccion" minOccurs="0" />
        <xs:element ref="clima" minOccurs="0" />
        <xs:element ref="tiempo" minOccurs="0" />
      </xs:sequence>
      <xs:attribute name="tipo" type="xs:NMTOKEN" use="required" />
      <xs:attribute name="nombre" type="xs:NMTOKEN" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="velocidad">
    <xs:complexType mixed="true" />
  </xs:element>
  <xs:element name="vmax">
    <xs:complexType mixed="true" />
  </xs:element>
</xs:schema>

=== noloman/V2V/src/xml/vehiculoNuevoPrueba.xml
<?xml version="1.0" encoding="UTF-8"?>
<vehiculo nombre="Vehiculo2" tipo="Coche" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:C:/Users/Manolo/Workspace/Proyecto/src/xml/XMLSchema.xsd" >
	<informacion_propia>
		<distancia>97.0</distancia>
		<velocidad>120</velocidad>
		<vmax>150</vmax>
		<aceleracion>0</aceleracion>
		<direccion>sur</direccion>
		<clima>despejado</clima>
		<tiempo>2009-05-18T16:00:00.00+02:00</tiempo>
	</informacion_propia>
	<informacion_ajena>
	<vehiculo tipo="Coche" nombre="Vehiculo9">
		<distancia>9.4</distancia>
		<velocidad>30</velocidad>
		<vmax>90</vmax>
		<aceleracion>0</aceleracion>
		<direccion>norte</direccion>
		<clima>nieve</clima>
		<tiempo>2009-05-19T09:08:45.296+02:00</tiempo>
	</vehiculo>
	<vehiculo tipo="Coche" nombre="Vehiculo9">
		<distancia>3.0</distancia>
		<velocidad>100</velocidad>
		<vmax>90</vmax>
		<aceleracion>0</aceleracion>
		<direccion>norte</direccion>
		<clima>nieve</clima>
		<tiempo>2009-05-19T13:35:53.195+02:00</tiempo>
	</vehiculo>
	<vehiculo tipo="Coche" nombre="Vehiculo4">
		<distancia>12.0</distancia>
		<velocidad>40</velocidad>
		<vmax>120</vmax>
		<aceleracion>2</aceleracion>
		<direccion>norte</direccion>
		<clima>despejado</clima>
		<tiempo>2009-05-19T14:56:12.585+02:00</tiempo>
	</vehiculo>
	<vehiculo tipo="Emergencias" nombre="Emergencias1">	
		<distancia>1.0</distancia>
		<velocidad>140</velocidad>
		<vmax>120</vmax>
		<aceleracion>2</aceleracion>
		<direccion>norte</direccion>
		<clima>despejado</clima>
		<tiempo>2009-05-19T10:10.585+02:00</tiempo>
	</vehiculo>
	</informacion_ajena>
</vehiculo>

=== noloman/V2V/src/xml/vehiculo.xml
<?xml version="1.0" encoding="UTF-8"?>
<vehiculo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" nombre="Vehiculo1" tipo="Coche" xsi:noNamespaceSchemaLocation="file:C:/Users/Manolo/Workspace/Proyecto/src/xml/XMLSchema.xsd">
	<informacion_propia>
		<distancia>3.0</distancia>
		<velocidad>100</velocidad>
		<vmax>120</vmax>
		<aceleracion>0</aceleracion>
		<direccion>norte</direccion>
		<clima>despejado</clima>
		<tiempo>2009-05-18T16:00:00.00+02:00</tiempo>
	</informacion_propia>
<informacion_ajena>
</informacion_ajena>
</vehiculo>
